<?php
// if( function_exists('acf_add_local_field_group') ):

	// acf_add_local_field_group(array (
	// 'key' => 'group_59b1896497500',
	// 'title' => 'Site Options',
	// 'fields' => array (
	// 	array (
	// 		'key' => 'field_59b189809efa8',
	// 		'label' => 'Logo',
	// 		'name' => 'logo',
	// 		'type' => 'image',
	// 		'instructions' => '',
	// 		'required' => 0,
	// 		'conditional_logic' => 0,
	// 		'wrapper' => array (
	// 			'width' => '',
	// 			'class' => '',
	// 			'id' => '',
	// 		),
	// 		'return_format' => 'array',
	// 		'preview_size' => 'thumbnail',
	// 		'library' => 'all',
	// 		'min_width' => '',
	// 		'min_height' => '',
	// 		'min_size' => '',
	// 		'max_width' => '',
	// 		'max_height' => '',
	// 		'max_size' => '',
	// 		'mime_types' => '',
	// 	),
	// 	array (
	// 		'key' => 'field_59bab0b687025',
	// 		'label' => 'Address',
	// 		'name' => 'address',
	// 		'type' => 'text',
	// 		'instructions' => '',
	// 		'required' => 0,
	// 		'conditional_logic' => 0,
	// 		'wrapper' => array (
	// 			'width' => '',
	// 			'class' => '',
	// 			'id' => '',
	// 		),
	// 		'default_value' => '',
	// 		'placeholder' => '',
	// 		'prepend' => '',
	// 		'append' => '',
	// 		'maxlength' => '',
	// 	),
	// 	array (
	// 		'key' => 'field_59bab0c287026',
	// 		'label' => 'City',
	// 		'name' => 'city',
	// 		'type' => 'text',
	// 		'instructions' => '',
	// 		'required' => 0,
	// 		'conditional_logic' => 0,
	// 		'wrapper' => array (
	// 			'width' => '',
	// 			'class' => '',
	// 			'id' => '',
	// 		),
	// 		'default_value' => '',
	// 		'placeholder' => '',
	// 		'prepend' => '',
	// 		'append' => '',
	// 		'maxlength' => '',
	// 	),
	// 	array (
	// 		'key' => 'field_59bab0cd87027',
	// 		'label' => 'State',
	// 		'name' => 'state',
	// 		'type' => 'text',
	// 		'instructions' => '',
	// 		'required' => 0,
	// 		'conditional_logic' => 0,
	// 		'wrapper' => array (
	// 			'width' => '',
	// 			'class' => '',
	// 			'id' => '',
	// 		),
	// 		'default_value' => '',
	// 		'placeholder' => '',
	// 		'prepend' => '',
	// 		'append' => '',
	// 		'maxlength' => '',
	// 	),
	// 	array (
	// 		'key' => 'field_59bab0d187028',
	// 		'label' => 'Zip',
	// 		'name' => 'zip',
	// 		'type' => 'text',
	// 		'instructions' => '',
	// 		'required' => 0,
	// 		'conditional_logic' => 0,
	// 		'wrapper' => array (
	// 			'width' => '',
	// 			'class' => '',
	// 			'id' => '',
	// 		),
	// 		'default_value' => '',
	// 		'placeholder' => '',
	// 		'prepend' => '',
	// 		'append' => '',
	// 		'maxlength' => '',
	// 	),
	// 	array (
	// 		'key' => 'field_59bab0d787029',
	// 		'label' => 'Latitude',
	// 		'name' => 'latitude',
	// 		'type' => 'text',
	// 		'instructions' => '',
	// 		'required' => 0,
	// 		'conditional_logic' => 0,
	// 		'wrapper' => array (
	// 			'width' => '',
	// 			'class' => '',
	// 			'id' => '',
	// 		),
	// 		'default_value' => '',
	// 		'placeholder' => '',
	// 		'prepend' => '',
	// 		'append' => '',
	// 		'maxlength' => '',
	// 	),
	// 	array (
	// 		'key' => 'field_59bab0e18702a',
	// 		'label' => 'Longitude',
	// 		'name' => 'longitude',
	// 		'type' => 'text',
	// 		'instructions' => '',
	// 		'required' => 0,
	// 		'conditional_logic' => 0,
	// 		'wrapper' => array (
	// 			'width' => '',
	// 			'class' => '',
	// 			'id' => '',
	// 		),
	// 		'default_value' => '',
	// 		'placeholder' => '',
	// 		'prepend' => '',
	// 		'append' => '',
	// 		'maxlength' => '',
	// 	),
	// 	array (
	// 		'key' => 'field_59bab2171ad20',
	// 		'label' => 'Phone',
	// 		'name' => 'phone',
	// 		'type' => 'text',
	// 		'instructions' => '',
	// 		'required' => 0,
	// 		'conditional_logic' => 0,
	// 		'wrapper' => array (
	// 			'width' => '',
	// 			'class' => '',
	// 			'id' => '',
	// 		),
	// 		'default_value' => '',
	// 		'placeholder' => '',
	// 		'prepend' => '',
	// 		'append' => '',
	// 		'maxlength' => '',
	// 	),
	// 	array (
	// 		'key' => 'field_59b197ea85273',
	// 		'label' => 'Social Media',
	// 		'name' => 'social_media',
	// 		'type' => 'repeater',
	// 		'instructions' => '',
	// 		'required' => 0,
	// 		'conditional_logic' => 0,
	// 		'wrapper' => array (
	// 			'width' => '',
	// 			'class' => '',
	// 			'id' => '',
	// 		),
	// 		'collapsed' => '',
	// 		'min' => 0,
	// 		'max' => 0,
	// 		'layout' => 'row',
	// 		'button_label' => 'Add Account',
	// 		'sub_fields' => array (
	// 			array (
	// 				'key' => 'field_59b1980a85274',
	// 				'label' => 'Social Media Type',
	// 				'name' => 'social_media_type',
	// 				'type' => 'select',
	// 				'instructions' => '',
	// 				'required' => 0,
	// 				'conditional_logic' => 0,
	// 				'wrapper' => array (
	// 					'width' => '',
	// 					'class' => '',
	// 					'id' => '',
	// 				),
	// 				'choices' => array (
	// 					'fa-rss' => 'Blog',
	// 					'fa-facebook' => 'Facebook',
	// 					'fa-google-plus' => 'Google+',
	// 					'fa-instagram' => 'Instagram',
	// 					'fa-linkedin' => 'LinkedIn',
	// 					'fa-pinterest-p' => 'Pinterest',
	// 					'fa-twitter' => 'Twitter',
	// 					'fa-youtube' => 'YouTube',
	// 				),
	// 				'default_value' => array (
	// 				),
	// 				'allow_null' => 0,
	// 				'multiple' => 0,
	// 				'ui' => 0,
	// 				'ajax' => 0,
	// 				'return_format' => 'value',
	// 				'placeholder' => '',
	// 			),
	// 			array (
	// 				'key' => 'field_59b1987085275',
	// 				'label' => 'URL',
	// 				'name' => 'url',
	// 				'type' => 'text',
	// 				'instructions' => '',
	// 				'required' => 0,
	// 				'conditional_logic' => 0,
	// 				'wrapper' => array (
	// 					'width' => '',
	// 					'class' => '',
	// 					'id' => '',
	// 				),
	// 				'default_value' => '',
	// 				'placeholder' => '',
	// 				'prepend' => '',
	// 				'append' => '',
	// 				'maxlength' => '',
	// 			),
	// 		),
	// 	),
	// 	array (
	// 		'key' => 'field_59b18a8f7308a',
	// 		'label' => 'Privacy Policy',
	// 		'name' => 'privacy_policy',
	// 		'type' => 'file',
	// 		'instructions' => '',
	// 		'required' => 0,
	// 		'conditional_logic' => 0,
	// 		'wrapper' => array (
	// 			'width' => '',
	// 			'class' => '',
	// 			'id' => '',
	// 		),
	// 		'return_format' => 'array',
	// 		'library' => 'all',
	// 		'min_size' => '',
	// 		'max_size' => '',
	// 		'mime_types' => '',
	// 	),
	// ),
	// 'location' => array (
	// 	array (
	// 		array (
	// 			'param' => 'options_page',
	// 			'operator' => '==',
	// 			'value' => 'acf-options',
	// 		),
	// 	),
	// ),
	// 'menu_order' => 0,
	// 'position' => 'normal',
	// 'style' => 'default',
	// 'label_placement' => 'top',
	// 'instruction_placement' => 'label',
	// 'hide_on_screen' => '',
	// 'active' => 1,
	// 'description' => '',
	// ));

// endif;